theme: jekyll-theme-architect
# Wotakoi: Love Is Hard for Otaku
![Facade](https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.imdb.com%2Ftitle%2Ftt8254880%2F&psig=AOvVaw1Z6O3Fosf0dn8-L9AMRDGz&ust=1702361754821000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCJCh3pDghoMDFQAAAAAdAAAAABAI)
